"""add_game_status_fields

Revision ID: b90938587d71
Revises: 12d2d8867c48
Create Date: 2026-01-29 01:53:33.898399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90938587d71'
down_revision: Union[str, Sequence[str], None] = '12d2d8867c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(), nullable=True))
    op.add_column('games', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('last_polled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'last_polled_at')
    op.drop_column('games', 'start_time')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
